esphome:
  name: esp-smoke
  friendly_name: esp-smoke
    
external_components:
  - source:
      type: git
      url: https://github.com/stefslon/esphome-thermoworks-smoke
    components: [thermoworks_smoke]

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: #redacted#

ota:
  password: #redacted#
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  manual_ip:
    static_ip: #redacted#
    gateway: #redacted#
    subnet: #redacted#

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: #redacted#
    password: #redacted#

captive_portal:

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12
  
thermoworks_smoke:
  id: thermoworks_smoke_receiver
  rf_channel: 10
  # -- when radio_id is not defined, unit goes into search mode
  #    watch ESPHome log for potential matches. Do NOT put Smoke unit
  #    into Connection/Pairing mode. Search may take up to 5 minutes.
  #radio_id: 0x123456789A 
  # -- if you are not able to find the unit, try uncommenting the line
  #    below, your unit might have a different address pattern
  #alt_radio_id: 1
  ce_pin: D4
  cs_pin: D1
  probe1_temp_sensor:
    name: "Smoke Probe 1 Temperature"
  probe1_min_sensor:
    name: "Smoke Probe 1 Min Alarm"
  probe1_max_sensor:
    name: "Smoke Probe 1 Max Alarm"
  probe2_temp_sensor:
    name: "Smoke Probe 2 Temperature"
  probe2_min_sensor:
    name: "Smoke Probe 2 Min Alarm"
  probe2_max_sensor:
    name: "Smoke Probe 2 Max Alarm"